config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :recipes
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allergen.rb
class Allergen < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  has_many :allergens, dependent: :destroy
  has_many :users, through: :allergens
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  validates :name, uniqueness: {case_sensitive: false}
  validates :user_id, :name, presence: true
  
  def user_name
    self.user.name
  end

  def ingredients_count 
  	self.ingredients.count
  end 

  def self.search(search)
  	if search
  		recipe = Recipe.find_by(name: search)
  		if recipe
  			if !recipe.ingredients.empty?
  				self.where(name: search)
  			else 
  				self.where(name: search)
  			end 
  		else
  			Recipe.all.sort_by do |recipe| recipe.ingredients.count end.reverse
  		end 
  	else
  		Recipe.all.sort_by do |recipe| recipe.ingredients.count end.reverse
    end 
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_many :allergens, dependent: :destroy
  has_many :ingredients, through: :allergens
  has_many :recipes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.search(params[:search])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(strong_params)
    if @recipe.errors.empty?
      redirect_to @recipe
    else 
      render :new 
    end
  end

  private

  def strong_params
    params.require(:recipe).permit!
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def destroy
   	@user = User.find(params[:id])
   	@user.destroy 
   	redirect_to recipes_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1>All Ingredients</h1>

<ul>
    <% @ingredients.each do |i| %>
        <li><%= link_to i.name, ingredient_path(i) %></li>
    <% end %>
</ul>

app/views/ingredients/show.html.erb
<h1> <%= @ingredient.name %> </h1>

<h2> Recipes using this ingredient </h2>

<ul>
  <% @ingredient.recipes.each do |r| %>
  <li> <%= link_to r.name, recipe_path(r) %> </li>
      <% end %>
    </ul>

<% if !@ingredient.users.empty? %>
 <h2>Users allergic to <%= @ingredient.name %></h2>
 <ul>
 	<% @ingredient.users.each do |u| %>
 		<li><%= link_to u.name, user_path(u) %></li>
 	<% end %>
 </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllergenLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>

<h2>Search for a recipe here: </h2>

<%= form_tag(recipes_path, method: "get") do %>
  <%= label_tag "Search for:" %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>

<ul>
    <% @recipes.each do |r| %>
        <li>Name: <%= link_to r.name, recipe_path(r) %></li><br># of Recipes: <%= r.ingredients_count %>
    <% end %>
</ul>

app/views/recipes/new.html.erb
<h1>Add a recipe below</h1>

<% if @recipe.errors %>
	<% @recipe.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
<% end %>

<%= form_for @recipe do |r| %>

  <%=r.label "Recipe Name" %>
  <%=r.text_field :name %>

  <%= r.label "User" %>
  <%= r.collection_select(:user_id, User.all, :id, :name, {:prompt => 'Select User'}) %>

  <%= r.submit "Create Recipe" %>

<% end %>

app/views/recipes/show.html.erb
<h1> <%= @recipe.name %> </h1>

<h2> Ingredients </h2>

<ul>
  <% @recipe.ingredients.each do |i| %>
  <li> <%= link_to i.name, ingredient_path(i) %> </li>
      <% end %>
    </ul>
<% if @recipe.user %>
	<h3> Made by <%= link_to @recipe.user_name, user_path(@recipe.user) %> </h3>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>

<h2> My Recipes </h2>

<ul>
  <% @user.recipes.each do |r| %>
  <li> <%= link_to r.name, recipe_path(r) %> </li>
      <% end %>
    </ul>

 <h2>I am allergic to:</h2>
 <ul>
 	<% @user.ingredients.each do |i| %>
 		<li><%= link_to i.name, ingredient_path(i) %></li>
 	<% end %>
 </ul>
    
<%= form_tag user_path(@user), method:"delete" do %>
	<%= submit_tag "Delete this user" %>
<% end %>